const PRODUCT_DISCLOSURES={
  'egg-whites':'Liquid egg whites. Brand-specific stabilizers and sodium may vary.',
  'good-culture':'Cultured skim milk, cream, sea salt, live and active cultures.',
  'fairlife-fat-free':'Ultra-filtered skim milk, lactase enzyme, vitamin A palmitate, vitamin D3.',
  'egglife-original':'Egg whites, xanthan gum, natural flavor, salt, nisin (natural preservative).',
  'oikos-pro':'Cultured reduced-fat milk, milk-protein concentrate, water, cane sugar, natural flavors, modified corn starch, stevia extract and live cultures; flavor formulas vary.',
  'boca-original':'Water, soy-protein concentrate, wheat gluten, methylcellulose, corn oil, yeast extract, caramel color, seasonings and salt; see source for the ordered current panel.',
  'boca-american':'Water, soy-protein concentrate, wheat gluten, cheese ingredients, methylcellulose, oils, seasonings and salt; see source for the ordered current panel.',
  'beyond-steak':'Water, wheat gluten, fava-bean protein, canola oil, rice protein, methylcellulose, natural flavors, potato starch, salt, potassium chloride and vitamins/minerals.',
  'magic-spoon':'Milk-protein blend, sweetener blend, oil, tapioca starch, natural flavors, salt and color ingredients; the exact panel varies substantially by flavor.',
  'impossible-beef':'Water, soy-protein concentrate, sunflower oil, coconut oil, natural flavors, methylcellulose, cultured dextrose, food starch, yeast extract, soy leghemoglobin, salt and vitamins/minerals.',
  'starbucks-bites':'Egg whites, cottage cheese, Monterey Jack cheese, red bell pepper, spinach, canola oil, rice starch, hot sauce and seasonings; restaurant formulation may change.',
  'chipotle-black-beans':'Black beans, water, onion, rice-bran oil, chipotle chili, cumin, garlic, oregano, black pepper, citrus juice and salt.',
  'chipotle-sofritas':'Organic tofu, water, chipotle chili, rice-bran oil, roasted poblano pepper, tomato paste, distilled vinegar, garlic, spices and salt.',
  'quest-cookie':'Protein blend (milk- and whey-protein isolates), butter, soluble corn fiber, erythritol, palm oil, unsweetened chocolate, cocoa butter, natural flavors, leavening, sea salt, sunflower lecithin and sweeteners; flavor formulas vary.',
  'kodiak-waffles':'Whole-grain wheat flour, wheat-protein isolate, whey-protein concentrate, brown sugar, leavening, oil, buttermilk, salt and natural flavor; check current box for the ordered panel.',
  'impossible-whopper':'Impossible patty plus bun, tomatoes, lettuce, mayonnaise, ketchup, pickles and sliced onions. Restaurant preparation and condiment formulation vary.'
};
const PRODUCT_META={
  'egg-whites':{family:'Egg-based breakfast anchors',useCases:['breakfast','meal'],simple:true},
  'good-culture':{family:'Cultured dairy anchors',useCases:['breakfast','snack'],simple:true},
  'fairlife-fat-free':{family:'Fast breakfast anchors',useCases:['breakfast','snack','travel'],simple:true},
  'egglife-original':{family:'Egg-based breakfast anchors',useCases:['breakfast','meal','travel'],simple:true},
  'oikos-pro':{family:'Cultured dairy anchors',useCases:['breakfast','snack','travel'],simple:false},
  'boca-original':{
    family:'BOCA burger variants',useCases:['meal'],simple:false,
    exactSku:{
      variant:'Original Vegan Veggie Burgers',size:'10 oz',upc:'0759283334455',servingSize:'1 burger (71g)',servingsPerPackage:4,
      dietaryLabels:['Vegan'],allergens:['Soy','Wheat','Sesame'],
      nutritionSourceUrl:'https://world.openfoodfacts.org/product/0759283334455/original-vegan-veggie-burgers-boca',nutritionCheckedAt:'2026-08-25',
      retailerHandoffs:[{type:'retailer-search',storeId:'target-bridgepointe-san-mateo',retailer:'Target',label:'Search Target',url:'https://www.target.com/s?searchTerm=0759283334455%20Original%20Vegan%20Veggie%20Burgers',checkedAt:'2026-08-25'}]
    }
  },
  'boca-american':{family:'BOCA burger variants',useCases:['meal'],simple:false},
  'beyond-steak':{
    family:'Plant-meat mains',useCases:['meal'],simple:false,
    exactSku:{
      variant:'Plant-Based Seared Tips',size:'10 oz',upc:'0810057290831',servingSize:'3.5 oz (100g)',servingsPerPackage:2.5,
      dietaryLabels:['Vegan','Soy-free'],allergens:['Wheat'],
      nutritionSourceUrl:'https://www.beyondmeat.com/en-US/products/beyond-steak',nutritionCheckedAt:'2026-08-13',
      retailerHandoffs:[
        {type:'exact-product',retailer:'Safeway on Instacart',label:'Check Safeway on Instacart',url:'https://www.instacart.com/products/27918479-beyond-steak-plant-based-seared-tips-original-10-oz?retailerSlug=safeway',checkedAt:'2026-08-25',availabilityStatus:'unknown',priceStatus:'unknown',detail:'Exact 10 oz order page; location, price and inventory are personalized after location or login.'},
        {type:'retailer-search',storeId:'target-bridgepointe-san-mateo',retailer:'Target',label:'Search Target',url:'https://www.target.com/s?searchTerm=0810057290831',checkedAt:'2026-08-25'}
      ]
    }
  },
  'magic-spoon':{family:'Fast breakfast anchors',useCases:['breakfast','snack'],simple:false},
  'impossible-beef':{family:'Plant-meat mains',useCases:['meal'],simple:false},
  'starbucks-bites':{family:'Restaurant breakfast builds',useCases:['breakfast','snack','travel'],simple:false,restaurantBuild:'Order the Egg White & Roasted Red Pepper Bites as listed; pair with another anchor if the meal target exceeds 12g.'},
  'chipotle-black-beans':{family:'Chipotle protein build',useCases:['meal','travel'],simple:true,restaurantBuild:'Add black beans to a bowl, salad or tacos; pair with sofritas for a seeded 16g combined protein example before other ingredients.'},
  'chipotle-sofritas':{family:'Chipotle protein build',useCases:['meal','travel'],simple:false,restaurantBuild:'Choose sofritas and add black beans for a seeded 16g combined protein example; re-check the restaurant calculator for the complete build.'},
  'quest-cookie':{
    family:'Portable protein snacks',useCases:['snack','travel'],simple:false,
    exactSku:{
      variant:'Chocolate Chip Protein Cookie',size:'2.08 oz',upc:'0888849005994',servingSize:'1 cookie (59g)',servingsPerPackage:1,
      dietaryLabels:['Vegetarian'],allergens:['Milk','Soy','Processed with egg, wheat, peanut and tree-nut equipment'],
      nutritionSourceUrl:'https://world.openfoodfacts.org/product/0888849005994/protein-cookie-chocolate-chip-quest',nutritionCheckedAt:'2026-08-25',
      retailerHandoffs:[{type:'retailer-search',storeId:'target-bridgepointe-san-mateo',retailer:'Target',label:'Search Target',url:'https://www.target.com/s?searchTerm=0888849005994%20Chocolate%20Chip%20Protein%20Cookie',checkedAt:'2026-08-25'}]
    }
  },
  'kodiak-waffles':{family:'Fast breakfast anchors',useCases:['breakfast'],simple:false},
  'impossible-whopper':{family:'Restaurant plant-meat meals',useCases:['meal','travel'],simple:false,restaurantBuild:'Order the menu item only if a full Whopper-style meal is the goal; ask the location about vegetarian preparation and cross-contact.'}
};
const PRODUCT_IMAGES={
  'boca-original':{path:'images/products/boca-original-0759283334455.jpg',upc:'0759283334455',variant:'Original Vegan Veggie Burgers · 10 oz',license:'CC BY-SA 3.0',attribution:'Open Food Facts contributor image',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',sourceUrl:'https://world.openfoodfacts.org/product/0759283334455/original-vegan-veggie-burgers-boca'},
  'beyond-steak':{path:'images/products/beyond-steak-0810057290831.jpg',upc:'0810057290831',variant:'Plant-Based Seared Tips · 10 oz',license:'CC BY-SA 3.0',attribution:'Open Food Facts contributor image',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',sourceUrl:'https://world.openfoodfacts.org/product/0810057290831/plant-based-seared-tips-beyond-steak'},
  'quest-cookie':{path:'images/products/quest-cookie-0888849005994.jpg',upc:'0888849005994',variant:'Chocolate Chip Protein Cookie · 2.08 oz',license:'CC BY-SA 3.0',attribution:'Open Food Facts contributor image',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',sourceUrl:'https://world.openfoodfacts.org/product/0888849005994/protein-cookie-chocolate-chip-quest'}
};
window.PROTEIN_PRODUCTS = [
  {id:'egg-whites',name:'Liquid egg whites',brand:'Seeded generic example',category:'Egg',calories:25,protein:5,sugar:0,fiber:0,sodium:75,price:4.49,servings:10,base:'Egg',diet:'vegetarian',soyFree:true,steviaFree:true,dairyFree:true,glutenFree:true,prep:'Cook',role:'anchor',verified:'2026-08-13',evidence:'USDA search reference',source:'https://fdc.nal.usda.gov/food-search/?query=liquid%20egg%20whites',stores:['Target','Safeway'],blurb:'The cleanest protein-return benchmark in the demo. Best when you want a hot meal without spending many calories on the protein base.',use:'Scramble, breakfast sandwich, fried rice add-in',tradeoff:'Requires cooking; exact-brand sodium varies.'},
  {id:'good-culture',name:'Low-fat cottage cheese',brand:'Good Culture',category:'Dairy',calories:80,protein:14,sugar:3,fiber:0,sodium:340,price:5.99,servings:4,base:'Dairy',diet:'vegetarian',soyFree:true,steviaFree:true,dairyFree:false,glutenFree:true,prep:'Ready now',role:'anchor',verified:'2026-08-13',evidence:'USDA branded record',source:'https://fdc.nal.usda.gov/food-search/?query=Good%20Culture%20low-fat%20cottage%20cheese',stores:['Target','Whole Foods'],blurb:'An unusually efficient ready-to-eat anchor with enough protein in a normal serving to matter.',use:'Snack, savory bowl, dip base',tradeoff:'Dairy and relatively salty; texture is polarizing.'},
  {id:'fairlife-fat-free',name:'Fat-free ultra-filtered milk',brand:'fairlife',category:'Milk & shakes',calories:80,protein:13,sugar:6,fiber:0,sodium:120,price:5.49,servings:6,base:'Dairy',diet:'vegetarian',soyFree:true,steviaFree:true,dairyFree:false,glutenFree:true,prep:'Ready now',role:'anchor',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://fairlife.com/ultra-filtered-milk/fat-free-skim-milk/',stores:['Safeway','Target','Costco'],blurb:'The easiest “same behavior, better return” swap: cereal, coffee and shakes gain real protein without changing the routine.',use:'Drink, cereal, coffee, shake base',tradeoff:'Dairy; local package size and price need a live check.'},
  {id:'egglife-original',name:'Original egg-white wrap',brand:'Egglife',category:'Wraps & breads',calories:35,protein:5,sugar:0,fiber:0,sodium:140,price:6.49,servings:6,base:'Egg',diet:'vegetarian',soyFree:true,steviaFree:true,dairyFree:true,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'USDA + retailer listing',source:'https://www.target.com/p/egglife-gluten-free-original-egg-white-wraps-6oz-6ct/-/A-81907833',stores:['Target','Whole Foods'],blurb:'A carrier that contributes protein instead of merely holding the filling. Pair two with a real filling for a useful meal.',use:'Wrap, quesadilla shell, breakfast roll-up',tradeoff:'Only 5 g per wrap, so ratio is excellent but serving size is small.'},
  {id:'oikos-pro',name:'Pro vanilla Greek yogurt',brand:'Oikos',category:'Dairy',calories:140,protein:20,sugar:6,fiber:0,sodium:85,price:2.19,servings:1,base:'Dairy',diet:'vegetarian',soyFree:true,steviaFree:false,dairyFree:false,glutenFree:true,prep:'Ready now',role:'anchor',verified:'2026-08-13',evidence:'USDA branded record',source:'https://fdc.nal.usda.gov/food-search/?query=Oikos%20Pro%20vanilla%20Greek%20yogurt',stores:['Target','Safeway'],blurb:'A complete snack-sized 20 g anchor. The catch is sweetener tolerance, not protein performance.',use:'Breakfast, snack, fruit bowl',tradeoff:'Current sweetener panel must be checked by flavor.'},
  {id:'boca-original',name:'Original Vegan Veggie Burger',brand:'BOCA',category:'Plant meat',calories:80,protein:14,sugar:1,fiber:4,sodium:390,price:5.99,servings:4,base:'Soy',diet:'vegan',soyFree:false,steviaFree:true,dairyFree:true,glutenFree:false,prep:'Heat',role:'anchor',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://www.kraftheinz.com/boca/products/00759283600154-original-vegan-veggie-burgers-with-non-gmo-soy',stores:['Safeway','Target'],blurb:'The sleeper within-brand winner: 14 g protein for 80 calories. Better protein economics than BOCA’s breaded Chik’n sibling.',use:'Burger, salad, bowl, breakfast plate',tradeoff:'Soy, wheat and notable sodium.'},
  {id:'boca-american',name:'All American Veggie Burger',brand:'BOCA',category:'Plant meat',calories:110,protein:14,sugar:1,fiber:4,sodium:450,price:5.99,servings:4,base:'Soy + dairy',diet:'vegetarian',soyFree:false,steviaFree:true,dairyFree:false,glutenFree:false,prep:'Heat',role:'anchor',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://www.kraftheinz.com/boca/products/00759283673219-all-american-veggie-burgers',stores:['Safeway'],blurb:'Same protein as BOCA Original Vegan with 30 more calories. Choose it for cheddar flavor, not superior macros.',use:'Cheesier burger or salad protein',tradeoff:'Contains soy, milk, wheat and sesame.'},
  {id:'beyond-steak',name:'Plant-Based Seared Tips',brand:'Beyond Steak',category:'Plant meat',calories:170,protein:21,sugar:0,fiber:2,sodium:300,price:7.99,servings:2.5,base:'Wheat + fava',diet:'vegan',soyFree:true,steviaFree:true,dairyFree:true,glutenFree:false,prep:'Heat',role:'anchor',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://www.beyondmeat.com/en-US/products/beyond-steak',stores:['Target','Whole Foods'],blurb:'A high-output vegan convenience anchor that avoids soy and gives 21 g in one realistic serving.',use:'Fajitas, rice bowl, salad, stir-fry',tradeoff:'Wheat-based, processed and more expensive than dry staples.'},
  {id:'magic-spoon',name:'High-protein cereal',brand:'Magic Spoon',category:'Breakfast',calories:140,protein:13,sugar:0,fiber:1,sodium:180,price:9.99,servings:5,base:'Milk protein',diet:'vegetarian',soyFree:false,steviaFree:false,dairyFree:false,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'Manufacturer family page',source:'https://magicspoon.com/collections/cereal',stores:['Target'],blurb:'Strong for cereal, but price and sweeteners matter. Pair with filtered milk if breakfast must carry 25–30 g.',use:'Fast breakfast or crunchy snack',tradeoff:'Premium price; sweetener and allergen profile varies by flavor.'},
  {id:'impossible-beef',name:'Beef Made From Plants',brand:'Impossible',category:'Plant meat',calories:240,protein:19,sugar:1,fiber:5,sodium:370,price:8.99,servings:3,base:'Soy',diet:'vegan',soyFree:false,steviaFree:true,dairyFree:true,glutenFree:true,prep:'Cook',role:'anchor',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://impossiblefoods.com/products/beef/ground-beef',stores:['Safeway','Target','Whole Foods'],blurb:'A legitimate main protein, but less calorie-efficient than lean dairy, egg or BOCA Original.',use:'Tacos, burgers, pasta sauce',tradeoff:'Soy, cooking required and higher calorie load.'},
  {id:'starbucks-bites',name:'Egg White & Roasted Red Pepper Bites',brand:'Starbucks',category:'Restaurant',calories:170,protein:12,sugar:3,fiber:1,sodium:470,price:5.75,servings:1,base:'Egg + dairy',diet:'vegetarian',soyFree:true,steviaFree:true,dairyFree:false,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'Official restaurant nutrition',source:'https://www.starbucks.com/menu/product/2122116/single/nutrition',stores:['DoorDash'],blurb:'A credible grab-and-go contribution. Good when convenience wins; not enough alone for a large meal target.',use:'Breakfast or travel snack',tradeoff:'Dairy, sodium and restaurant price.'},
  {id:'chipotle-black-beans',name:'Black beans',brand:'Chipotle',category:'Restaurant',calories:130,protein:8,sugar:1,fiber:7,sodium:210,price:1.75,servings:1,base:'Legume',diet:'vegan',soyFree:true,steviaFree:true,dairyFree:true,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'Official restaurant calculator',source:'https://www.chipotle.com/nutrition-calculator',stores:['DoorDash'],blurb:'Useful soy-free support with fiber. Stack with sofritas if the bowl needs a more meaningful protein base.',use:'Bowl, tacos, salad',tradeoff:'Good food and useful support, but 8 g is not a full anchor.'},
  {id:'chipotle-sofritas',name:'Sofritas',brand:'Chipotle',category:'Restaurant',calories:150,protein:8,sugar:5,fiber:3,sodium:560,price:3.50,servings:1,base:'Soy',diet:'vegan',soyFree:false,steviaFree:true,dairyFree:true,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'Official restaurant calculator',source:'https://www.chipotle.com/nutrition-calculator',stores:['DoorDash'],blurb:'A useful plant filling, not a giant protein serving. Combine with black beans to reach about 16 g before other ingredients.',use:'Bowl, tacos, salad',tradeoff:'Soy and high sodium; the rest of the bowl determines total efficiency.'},
  {id:'quest-cookie',name:'Chocolate Chip Protein Cookie',brand:'Quest',category:'Snack',calories:250,protein:15,sugar:1,fiber:9,sodium:220,price:2.89,servings:1,base:'Milk + whey',diet:'vegetarian',soyFree:true,steviaFree:false,dairyFree:false,glutenFree:true,prep:'Ready now',role:'support',verified:'2026-08-13',evidence:'Manufacturer family page',source:'https://www.questnutrition.com/collections/protein-cookies',stores:['Target','Safeway'],blurb:'Better protein than an ordinary cookie, but still a 250-calorie treat—not interchangeable with a lean anchor.',use:'Dessert or portable snack',tradeoff:'Dairy, sweeteners and calorie density.'},
  {id:'kodiak-waffles',name:'Buttermilk & Vanilla Power Waffles',brand:'Kodiak',category:'Breakfast',calories:240,protein:12,sugar:8,fiber:3,sodium:360,price:6.49,servings:4,base:'Wheat + whey',diet:'vegetarian',soyFree:false,steviaFree:true,dairyFree:false,glutenFree:false,prep:'Heat',role:'support',verified:'2026-08-13',evidence:'Official manufacturer',source:'https://kodiakcakes.com/products/buttermilk-vanilla-power-waffles',stores:['Target','Safeway'],blurb:'A convenient breakfast with real protein, but the waffles alone do not finish a protein-first breakfast.',use:'Breakfast with yogurt or filtered milk',tradeoff:'Wheat, dairy and only supporting efficiency.'},
  {id:'impossible-whopper',name:'Impossible Whopper',brand:'Burger King',category:'Restaurant',calories:630,protein:25,sugar:14,fiber:4,sodium:1350,price:7.49,servings:1,base:'Soy',diet:'vegetarian',soyFree:false,steviaFree:true,dairyFree:true,glutenFree:false,prep:'Ready now',role:'halo',verified:'2026-08-13',evidence:'Official restaurant menu',source:'https://www.bk.com/menu',stores:['DoorDash'],blurb:'A satisfying full meal with 25 g protein, but poor protein return. Buy it because you want the Whopper—not because plant-based means lean.',use:'Occasional fast-food meal',tradeoff:'High calories and sodium; ask locally about vegetarian preparation.'}
].map(p=>({...p,...PRODUCT_META[p.id],image:PRODUCT_IMAGES[p.id]||null,eggFree:!p.base.toLowerCase().includes('egg'),efficiency:+(p.protein/p.calories*100).toFixed(1),proteinCalories:Math.round(p.protein*4/p.calories*100),pricePer25:+(p.price/(p.protein*p.servings)*25).toFixed(2),servingsFor20:+(20/p.protein).toFixed(1),caloriesFor20:Math.round(20/p.protein*p.calories),servingsFor30:+(30/p.protein).toFixed(1),caloriesFor30:Math.round(30/p.protein*p.calories),ingredients:PRODUCT_DISCLOSURES[p.id],ingredientStatus:'Seed transcription for interaction testing—not a current-package guarantee',availability:p.id==='magic-spoon'?'demo-unavailable':'demo-listed',availabilityLabel:p.id==='magic-spoon'?'Demo state: unavailable':'Seeded listing—not live stock',crossContact:p.category==='Restaurant'?'Restaurant cross-contact check required':'Exact package/manufacturer handling check required',sourceStatus:'Seed reference dated 2026-08-13; may be a search, family, manufacturer or menu page—not proof of a current exact SKU listing',actionLabel:p.category==='Restaurant'?'Open restaurant menu/source':'Open product source/listing'}));